Repository Rote-Beete/juntagrico-docker, pull requests merged in 2021-02, with the labels that each got.

#14 Do not login and push to Docker Hub on PR from fork
  .github/workflows/action.yml
Labels: bug

#19 Re-add step id for tag extraction
  .github/workflows/action.yml
Labels: bug

#16 start.py: Don't run makemigrations
  start.py
Labels: bug, enhancement

#24 Add faker dependency for generate_testdata_advanced
  requirements.txt
Labels: dependencies

#23 make USER instruction more explicit
  Dockerfile
Labels: bug

#22 split workflow for push and PR
  .github/workflows/action.yml
Labels: bug
